In [1]:
import tensorflow as tf

In [4]:
d0 = tf.ones((1,))

d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [15]:
d1 = tf.ones((2,))

d1.numpy()

array([1., 1.], dtype=float32)

In [14]:
d2 = tf.ones((2,2))

d2.numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [12]:
d3 = tf.ones((2,2,2))

print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [26]:
from tensorflow import constant, add, multiply, matmul
from tensorflow import Variable

In [20]:
a = constant([1,3])
b = constant([4,5])

add(a,b).numpy()

array([5, 8])

In [22]:
b = constant(([1,3],[5,7]))
c = constant(([4,5],[6,9]))

add(b,c).numpy()

array([[ 5,  8],
       [11, 16]])

In [ ]:
## multiply() - must have the same shape
## matmul - matrix multiplication


## reduce_sum(A) - sum over all dimensions of A
## reduce_sum(A, i) - sum over all dimension(s) i

In [43]:
A = ones(([2,3,4]))

print(A)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


In [44]:
from tensorflow import ones, reduce_sum

reduce_sum(A).numpy()

24.0

In [47]:
reduce_sum(A,0).numpy()

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)

In [48]:
reduce_sum(A,1).numpy()

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)

In [50]:
reduce_sum(A,2).numpy()

array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)

In [ ]:
def compute_gradient(x0):
  	# Define x as a variable with an initial value of x0
	x = Variable(x0)
	with GradientTape() as tape:
		tape.watch(x)
        # Define y using the multiply operation
		y = multiply(x,x)
    # Return the gradient of y with respect to x
	return tape.gradient(y, x).numpy()

In [ ]:
# Define a linear regression model
def linear_regression(intercept, slope, features = size_log):
	return features * slope + intercept

# Set loss_function() to take the variables as arguments
def loss_function(intercept, slope, features = size_log, targets = price_log):
	# Set the predicted values
	predictions = linear_regression(intercept, slope, features)
    
    # Return the mean squared error loss
	return keras.losses.mse(targets, predictions)

# Compute the loss for different slope and intercept values
print(loss_function(0.1, 0.1).numpy())
print(loss_function(0.1, 0.5).numpy())

In [ ]:
# Initialize an adam optimizer
opt = keras.optimizers.Adam(0.5)

for j in range(100):
	# Apply minimize, pass the loss function, and supply the variables
	opt.minimize(lambda: loss_function(intercept,slope), var_list=[intercept, slope])

	# Print every 10th value of the loss
	if j % 10 == 0:
		print(loss_function(intercept, slope).numpy())

# Plot data and regression line
plot_results(intercept, slope)